- name: change the home directory owner
  file: 
    path: "{{ home_automation_dir }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    state: directory
    mode: '755'
  become: yes

- name: clone home automation repo
  git:
    repo: git@github.com:shiftux/home_automation.git
    dest: "{{ home_automation_dir }}"
    accept_hostkey: yes
