version: '3.1'
services:
  nginx:
    container_name: 'nginx'
    image: nginx:latest
    depends_on:
      - home-assistant
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/nginx-certbot/nginx.conf:/etc/nginx/conf.d/default.conf
      - /opt/nginx-certbot/letsencrypt-site:/usr/share/nginx/html
      - /opt/nginx-certbot/dh-param/:/etc/ssl/certs/
      - /opt/nginx-certbot/docker-volumes/etc/letsencrypt/live/hass.shiftux.org-0001/fullchain.pem:/etc/letsencrypt/live/hass.shiftux.org/fullchain.pem
      - /opt/nginx-certbot/docker-volumes/etc/letsencrypt/live/hass.shiftux.org-0001/privkey.pem:/etc/letsencrypt/live/hass.shiftux.org/privkey.pem
    restart: unless-stopped
    networks:
      - docker-network

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - /mnt/nas_pi/mosquitto_storage/config/:/mosquitto/config/
      - /mnt/nas_pi/mosquitto_storage/log:/mosquitto/log
      - /mnt/nas_pi/mosquitto_storage/data:/mosquitto/data
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - docker-network

  home-assistant:
    image: homeassistant/raspberrypi4-64-homeassistant:0.110.4
    container_name: home-assistant
    environment:
      - TZ=Europe/Zurich
    volumes:
      - /opt/home_automation/home-assistant/config/:/config/
      - /mnt/nas_pi/hass_storage/.storage:/config/.storage
    ports:
      - "8123:8123"
    restart: unless-stopped
    depends_on:
      - mosquitto
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: 30s
      timeout: 10s
      retries: 6
    networks:
      - docker-network

  weather-forecast:
    image: nginx:latest
    container_name: weather-forecast
    volumes:
      - /opt/home_automation/local-weather-sites/forecast:/usr/share/nginx/html
      - /opt/home_automation/local-weather-sites/forecast/config:/etc/nginx/conf.d
    ports:
      - "8080:80"
    restart: unless-stopped

  weather-radar:
    image: nginx:latest
    container_name: weather-radar
    volumes:
      - /opt/home_automation/local-weather-sites/radar:/usr/share/nginx/html
      - /opt/home_automation/local-weather-sites/radar/config:/etc/nginx/conf.d
    ports:
      - "8081:80"
    restart: unless-stopped

  weather-daily:
    image: nginx:latest
    container_name: weather-daily
    volumes:
      - /opt/home_automation/local-weather-sites/daily:/usr/share/nginx/html
      - /opt/home_automation/local-weather-sites/daily/config:/etc/nginx/conf.d
    ports:
      - "8082:80"
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1003
      - PGID=1003
      - TZ=Europe/Zurich
      - FILE__USER=/home/user
      - FILE__PASS=/home/pass
    volumes:
      - /mnt/nas_pi/transmission_storage/config:/config
      - /mnt/ext_T7/media:/downloads
      - /mnt/nas_pi/transmission_storage/watch:/watch
      - ./secret_transmission_pw:/home/pass
      - ./secret_transmission_user:/home/user
    ports:
      - 9091:9091
    restart: unless-stopped
    networks:
      - docker-network

  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /mnt/nas_pi/plex_storage/config:/config
      - /mnt/ext_T7/plex_transcode:/transcode
      - /mnt/ext_T7/media:/data
    environment:
      - PLEX_UID=1003
      - PLEX_GID=1003
      - TZ=Europe/Zurich
    restart: unless-stopped
    expose:
      - 32400
    networks:
      - docker-network

  sickchill:
    image: linuxserver/sickchill
    container_name: sickchill
    environment:
      - PUID=1003
      - PGID=1003
      - TZ=Europe/Zurich
    volumes:
      - /mnt/nas_pi/sickchill_storage/config:/config
      - /mnt/ext_T7/media:/downloads
    restart: unless-stopped
    ports:
      - 8081:8081
    networks:
      - docker-network

  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    environment:
      - PUID=1003
      - PGID=1003
      - TZ=Europe/Zurich
      - UMASK_SET=022
    volumes:
      - /mnt/nas_pi/couchpotato_storage/config:/config
      - /mnt/ext_T7/media:/downloads
      - /mnt/ext_T7/media/movies:/movies
    restart: unless-stopped
    ports:
      - 5050:5050
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
