version: '3.1'
services:
  # nginx:
  #   container_name: 'nginx'
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /data/nginx-certbot/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - /data/nginx-certbot/letsencrypt-site:/usr/share/nginx/html
  #     - /data/nginx-certbot/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
  #     - /data/nginx-certbot/docker-volumes/etc/letsencrypt/live/plex.shiftux.org/fullchain.pem:/etc/letsencrypt/live/plex.shiftux.org/fullchain.pem
  #     - /data/nginx-certbot/docker-volumes/etc/letsencrypt/live/plex.shiftux.org/privkey.pem:/etc/letsencrypt/live/plex.shiftux.org/privkey.pem
  #   networks:
  #     - docker-network

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - /Users/tgdmosaa/development/home_automation/mosquitto/config/:/mosquitto/config/
      - /Users/tgdmosaa/development/home_automation/mosquitto/log:/mosquitto/log
      - /Users/tgdmosaa/development/home_automation/mosquitto/data:/mosquitto/data
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"

# networks:
#   docker-network:
#     driver: bridge
