- name: set swapoff
  command: swapoff -a
  become: yes

- name: Remove swap line in fstab
  lineinfile:
    path: /etc/fstab
    regex: 'swapfile'
    state: absent
  become: yes

- name: disable wifi
  systemd:
    name: wpa_supplicant
    state: stopped
    enabled: no
  become: yes

