- name: create mosquitto folder
  file:
    state: directory
    path: "{{mosquitto_data_folder}}"
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ group }}"

- name: create mosquitto log folder
  file:
    state: directory
    path: "{{mosquitto_data_folder}}/log"
    mode: '0777'
    owner: "{{ user }}"
    group: "{{ group }}"

- name: create mosquitto data folder
  file:
    state: directory
    path: "{{mosquitto_data_folder}}/data"
    mode: '0777'
    owner: "{{ user }}"
    group: "{{ group }}"

- name: create mosquitto config folder
  file:
    state: directory
    path: "{{mosquitto_data_folder}}/config"
    mode: '0777'
    owner: "{{ user }}"
    group: "{{ group }}"

- name: copy config file
  copy:
    src: ../files/mosquitto_conf
    dest: "{{mosquitto_data_folder}}/config/mosquitto.conf"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0664'
    force: yes
    backup: no

- name: copy password file
  copy:
    src: ../files/passwordfile.pw
    dest: "{{mosquitto_data_folder}}/config/passwordfile.pw"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0644'
    force: yes
    backup: no
