- name: install docker
  package:
    name: 
      - docker.io
      - docker-compose
    state: latest
  become: yes

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: [docker]
    append: yes
  become: yes

- name: start docker and ensure it starts on boot
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

# k8s and docker should rely on the same cgroup driver, k8s suggests systemd
# https://askubuntu.com/questions/1189480/raspberry-pi-4-ubuntu-19-10-cannot-enable-cgroup-memory-at-boostrap
- name: check if cgroupfs is default cgroup driver
  shell: docker info | grep -i cgroup
  register: cgroup_driver

- name: start docker and ensure it starts on boot
  systemd:
    daemon_reload: yes
    name: docker
    state: restarted
    enabled: yes
  become: yes
  when: "cgroup_driver.stdout != \" Cgroup Driver: cgroupfs\""

- name: backup /boot/firmware/cmdline.txt
  copy: 
    remote_src: yes
    src: /boot/firmware/cmdline.txt
    dest: /boot/firmware/cmdline.txt.bkp
    force: no
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: make sure cgroup cpu/mem are enabled
  copy:
    src: ../files/cmdline.txt
    dest: /boot/firmware/cmdline.txt
    owner: root
    group: root
    mode: '0755'
    force: yes
  become: yes
  when: "cgroup_driver.stdout != \" Cgroup Driver: cgroupfs\""

- name: Reboot
  reboot:
  become: yes
  when: "cgroup_driver.stdout != \" Cgroup Driver: cgroupfs\""
