- name: install docker
  package:
    name: 
      - docker.io
      - docker-compose
    state: latest
  become: yes

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: [docker]
    append: yes
  become: yes

- name: start docker and ensure it starts on boot
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
