- name: install docker
  package:
    name: 
      - docker.io
      - docker-compose
    state: latest
  become: yes

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: [docker]
    append: yes
  become: yes
