version: '3'
services:
  prometheus:
    image: prom/prometheus-linux-arm64
    container_name: prometheus
    user: root
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_db:/var/lib/prometheus
      - ./prometheus_db:/prometheus
      - ./prometheus_db:/etc/prometheus
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.route-prefix=/'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - '9090:9090'
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - '9093:9093'
    volumes:
      - ./alertmanager.yml.secret:/alertmanager.yml
      - ./notifications.tmpl:/notifications.tmpl
    command:
      - '--config.file=/alertmanager.yml'
    restart: unless-stopped
    networks:
      - monitor-net

# installed native
  # node-exporter:
  #   container_name: node-exporter
  #   image: prom/node-exporter
  #   ports:
  #     - '9100:9100'
  #   networks:
  #     - monitor-net

  cadvisor:
    image: budry/cadvisor-arm:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - '8090:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - '-docker_only=true'
      - '-housekeeping_interval=20s'
      - '-disable_metrics=disk'
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest-ubuntu
    container_name: grafana
    restart: unless-stopped
    # environment:
    #   - GF_SECURITY_ADMIN_PASSWORD=secure_pass
    volumes:
      - ./grafana_db:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
