#automation: 
  - alias: "TV turned on"
    trigger:
      platform: state
      entity_id: "switch.tv_samsung"
      to: 'on'
    action:
      - service: python_script.set_state
        data_template:
          entity_id: binary_sensor.tv_status
          allow_create: False
          state: 'on'

  - alias: "TV turned off"
    trigger:
      platform: state
      entity_id: "switch.tv_samsung"
      to: 'off'
    action:
      - service: python_script.set_state
        data_template:
          entity_id: binary_sensor.tv_status
          allow_create: False
          state: 'off'

  - alias: "LMS switched shuffle off"
    trigger:
      platform: state
      entity_id: "binary_sensor.lms_shuffle"
      to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.lms_shuffle

  - alias: "LMS switched shuffle on"
    trigger:
      platform: state
      entity_id: "binary_sensor.lms_shuffle"
      to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.lms_shuffle

  - alias: "Sync dining room light relays on"
    trigger:
      platform: mqtt
      topic: "light/sonoff-4ch/cmnd/POWER3"
    action:
      - service_template: mqtt.publish
        data_template:
          topic: "light/sonoff-4ch/cmnd/POWER4"
          payload: '{{ trigger.payload }}'

  # - alias: "Sync dining room light relays off"
  #   trigger:
  #     platform: mqtt
  #     topic: "light/sonoff-4ch/cmnd/POWER3"
  #     payload: 'OFF'
  #   action:
  #     - service: mqtt.publish
  #       data:
  #         topic: "light/sonoff-4ch/cmnd/POWER4"
  #         payload: 'OFF'
