#automation:
  - alias: "LMS switched shuffle off"
    trigger:
      platform: state
      entity_id: "binary_sensor.lms_shuffle"
      to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.lms_shuffle

  - alias: "LMS switched shuffle on"
    trigger:
      platform: state
      entity_id: "binary_sensor.lms_shuffle"
      to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.lms_shuffle

  - alias: "Sync dining room light relays on"
    trigger:
      platform: mqtt
      topic: "light/sonoff-4ch/cmnd/POWER3"
    action:
      - service_template: mqtt.publish
        data_template:
          topic: "light/sonoff-4ch/cmnd/POWER4"
          payload: '{{ trigger.payload }}'

  - alias: "Sync kitchen light with kitchen led"
    trigger:
      platform: mqtt
      topic: "light/sonoff-kitchen/stat/POWER"
    action:
      - service_template: mqtt.publish
        data_template:
          topic: "light/shelly-kitchen-led/cmnd/POWER"
          payload: '{{ trigger.payload }}'