#binary_sensor:
- platform: template
  sensors:
    lms_shuffle:
      friendly_name: "Shuffle Sensor"
      value_template: >-
        {{ is_state_attr('media_player.picorelivingroom_2', 'shuffle', 'song') }}
