#homeassistant:
  # Name of the location where HA is running
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  time_zone: !secret time_zone
  elevation: !secret elevation
