#light:
  - platform: mqtt
    name: "Entry"
    command_topic: "light/sonoff-entry/cmnd/POWER"
    state_topic: "light/sonoff-entry/stat/RESULT"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "light/sonoff-entry/tele/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true

  - platform: mqtt
    name: "Kitchen"
    command_topic: "light/sonoff-kitchen/cmnd/POWER"
    state_topic: "light/sonoff-kitchen/stat/RESULT"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "light/sonoff-kitchen/tele/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true

  - platform: mqtt
    schema: template
    name: "living room"
    command_topic: 'light/sonoff-4ch/cmnd/POWER1'
    state_topic: 'sensor/light/livingRoom'
    state_template: '{{ value | lower }}'
    availability_topic: 'light/sonoff-4ch/tele/LWT'
    command_on_template: >-
      {% if is_state('sensor.light_sensor_livingRoom', 'OFF') %}
        TOGGLE
      {% else %}
        ""
      {% endif %}
    command_off_template: >-
      {% if is_state('sensor.light_sensor_livingRoom', 'ON') %}
        TOGGLE
      {% else %}
        ""
      {% endif %}
    payload_available: 'Online'
    payload_not_available: 'Offline'
    qos: 1
    retain: true

  - platform: mqtt
    schema: template
    name: "dining room"
    command_topic: "light/sonoff-4ch/cmnd/POWER3"
    state_topic: "sensor/light/diningRoom"
    state_template: '{{ value | lower }}'
    availability_topic: "light/sonoff-4ch/tele/LWT"
    command_on_template: >-
      {% if is_state('sensor.light_sensor_diningroom', 'OFF') %}
        TOGGLE
      {% else %}
        ""
      {% endif %}
    command_off_template: >-
      {% if is_state('sensor.light_sensor_diningroom', 'ON') %}
        TOGGLE
      {% else %}
        ""
      {% endif %}
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true

  - platform: mqtt
    name: "Office"
    command_topic: "light/shelly-office/cmnd/POWER"
    state_topic: "light/shelly-office/stat/RESULT"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "light/shelly-office/tele/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true

  - platform: group
    name: All Lights
    entities:
      - light.kitchen
      - light.entry
      - light.dining_room
      - light.living_room
      - light.office
