  - platform: mqtt
    name: "Dual Red"
    command_topic: "test/sonoff-dual/cmnd/POWER2"
    state_topic: "test/sonoff-dual/tele/STATE"
    state_value_template: "{{value_json.POWER2}}"
    availability_topic: "test/sonoff-dual/tele/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Dual White"
    command_topic: "test/sonoff-dual/cmnd/POWER1"
    state_topic: "test/sonoff-dual/tele/STATE"
    state_value_template: "{{value_json.POWER1}}"
    availability_topic: "test/sonoff-dual/tele/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Basic"
    command_topic: "test/sonoff-basic/cmnd/POWER"
    state_topic: "test/sonoff-basic/tele/STATE"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "test/sonoff-basic/tele/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true

