# https://www.home-assistant.io/integrations/swiss_hydrological_data/  
  platform: swiss_hydrological_data
  station: !secret river_station
  monitored_conditions:
    - temperature
    - level
    - discharge
