  - platform: broadlink
    host: !secret broadlink_ip
    mac: !secret broadlink_mac
    timeout: 15
    switches:
      projector:
        friendly_name: "Projector"
        command_on: 'JgAgAQABKZIVNhQ2FBEUERQSFBEUERQ2FDYUEhQ2FBEUNhQSFDYUERQRFBEUEhQRFDYUERQRFDcUNhQ2FDYVNhQRFDYUNhQSFAAFQQABKpIVNRQ2FBEUEhQRFBEUERQ2FDcUERQ2FBEUNxQRFDYUERQRFBIUERQRFDYUERQSFDYUNhQ2FDcUNhQRFDYUNhQSFAAFQQABKpIVNRQ2FBIUERQRFBEUEhQ2FDYUERQ2FBIUNhQRFDYUEhQRFBEUERQRFDcUERQRFDYUNxQ2FDYUNhQSEzcUNhQRFAAFQgABKpEVNhQ2FBEUERQSFBEUERQ2FDYUEhQ2FBEUNhQSFDYUERQRFBEUEhQRFDYUERQSEzcUNhQ2FDYUNxQRFDYUNhQSFAANBQAAAAAAAAAA='
        command_off: 'JgAgAQABK5EVNRU2FBEUERUQFREUERQ2FTUVERQ2FBEVNRURFDYUERU1FREUERQRFTUVEBURFDYUERU1FTYUNhQRFTUVNhQRFAAFQgABKpEVNhQ2FBEVEBUQFREUERU1FTUVERQ2FBEVNRURFDYUERU1FRAVERQRFTUVEBURFDYUERU1FTUVNhQRFTUVNRURFAAFQQABKpIVNRQ2FBIUERQRFBEUEhQ2FDYUERQ2FBIUNhQRFDYUEhQ2FBEUERQSFDYUERQRFDYUEhQ2FDYUNhQSFDYUNhQRFAAFQgABKpIVNRQ3FBEUERQRFBEUEhQ2FDYUERQ3FBEUNhQRFDcUERQ2FBEUEhQRFDYUERQSEzcUERQ2FDYUNxQRFDYUNhQSFAANBQAAAAAAAAAA='

  - platform: broadlink
    host: !secret broadlink_ip
    mac: !secret broadlink_mac
    timeout: 15
    switches:
      nad_receiver_power:
        friendly_name: "NAD Receiver"
        command_on: 'JgBIAAABKI4XNhQ1FDYTEhMSFBEUERQ1FBEUEhM2FDUUNRQ2FDUUERQ2ExITNhQRFBEUNhMSExIUERQ1FBEUNhM2FBEUNRQ2EwANBQ=='
        command_off: 'JgBQAAABKJEUNhQ1FDUUEhMSExIUERQ1FBEUERQ2FDUUNRQ2FDUUERQRFBEUERQ2FBEUERQ1FDYTNhQ1FDYTEhQ1FDUUERQSEwAE9QABKEgUAA0FAAAAAAAAAAA='

  - platform: broadlink
    host: !secret broadlink_ip
    mac: !secret broadlink_mac
    timeout: 15
    switches:
      nad_receiver_vol_up:
        friendly_name: "Volume Up"
        command_on: 'JgBQAAABKJIUNRQ1FDYUERQRFBEUERQ1FBITEhQ1FDUUNhQ1FDUUEhMSExITEhQ1FBEUERQRFDYUNRQ1FDYUERQ1FDUUNhQRFAAE8wABKEgUAA0FAAAAAAAAAAA='
        command_off: 'JgBQAAABKJIUNRQ1FDYUERQRFBEUERQ1FBITEhQ1FDUUNhQ1FDUUEhMSExITEhQ1FBEUERQRFDYUNRQ1FDYUERQ1FDUUNhQRFAAE8wABKEgUAA0FAAAAAAAAAAA='

  - platform: broadlink
    host: !secret broadlink_ip
    mac: !secret broadlink_mac
    timeout: 15
    switches:
      nad_receiver_vol_down:
        friendly_name: "Volume Down"
        command_on: 'JgBIAAABKJIUNRQ1FDYUERQRFBEUERQ1FBITEhM2FDUUNhM2FDUUERQRFBITNhQ1FBEUERQSEzYUNRQ1FBITEhQ1FDUUNhQRFAANBQ=='
        command_off: 'JgBIAAABKJIUNRQ1FDYUERQRFBEUERQ1FBITEhM2FDUUNhM2FDUUERQRFBITNhQ1FBEUERQSEzYUNRQ1FBITEhQ1FDUUNhQRFAANBQ=='

  - platform: broadlink
    host: !secret broadlink_ip
    mac: !secret broadlink_mac
    timeout: 15
    switches:
      nad_receiver_select_opt1:
        friendly_name: "Music input"
        command_on: 'JgAwAB4cPDkeHTs5Hh07HR0dHhweHR4cHgALph0dOzoeHTs5Hh07HB4dHhweHR4cHgANBQAAAAAAAAAA'
        command_off: 'JgAwAB4cPDkeHTs5Hh07HR0dHhweHR4cHgALph0dOzoeHTs5Hh07HB4dHhweHR4cHgANBQAAAAAAAAAA'

  - platform: broadlink
    host: !secret broadlink_ip
    mac: !secret broadlink_mac
    timeout: 15
    switches:
      nad_receiver_select_opt2:
        friendly_name: "TV input"
        command_on: 'JgAYAB4dHR0eHB4dOzodHTsdHhweHR06OwANBQ=='
        command_off: 'JgAYAB4dHR0eHB4dOzodHTsdHhweHR06OwANBQ=='

  - platform: template
    switches:
      lms_shuffle:
        friendly_name: "Shuffle"
        value_template: "{{ is_state_attr('media_player.picorelivingroom', 'shuffle', 'song') }}"
        turn_on:
          service:  squeezebox.call_method
          data:
            entity_id: "media_player.picorelivingroom"
            command: "playlist"
            parameters: ["shuffle","1"]
        turn_off:
          service:  squeezebox.call_method
          data:
            entity_id: "media_player.picorelivingroom"
            command: "playlist"
            parameters: ["shuffle","0"]
        icon_template: >-
          {% if is_state_attr('media_player.picorelivingroom', 'shuffle', 'song')%}
            mdi:shuffle-variant
          {% else %}
            mdi:shuffle-disabled
          {% endif %}

  - platform: mqtt
    unique_id: irrigation_balcony_north_switch
    name: "Irrigation Balcony North"
    command_topic: "irrigation/balcony_north/cmnd/POWER"
    state_topic: "irrigation/balcony_north/stat/RESULT"
    value_template: "{{value_json.POWER}}"
    availability_topic: "irrigation/balcony_north/tele/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true
