{
 "title": "IOT Devices",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sonoff-4CH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"sonoff-4CH\"}"
    }
   ]
  },
  {
   "title": "Sonoff-Kitchen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"sonoff-kitchen\"}"
    }
   ]
  },
  {
   "title": "Sonoff-Entry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"sonoff-entry\"}"
    }
   ]
  },
  {
   "title": "Sonoff-Irrigation-North ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"sonoff-irrigation-north\"}"
    }
   ]
  },
  {
   "title": "IR Puck",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"tasmota-IR-puck\"}"
    }
   ]
  },
  {
   "title": "Shrlly Office",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"shelly-office\"}"
    }
   ]
  },
  {
   "title": "Device details",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "expr": "tasmota_info" }
   ]
  },
  {
   "title": "Free Memory [kb]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 12 },
   "targets": [
    { "expr": "tasmota_memory_free_bytes/1024", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}