---

# this includes apt steps, only works on debian so far
- name: System Setup
  hosts: RPi4
  vars:
    ansible_ssh_user: pi
    ansible_port: "{{ ssh_port }}"
    home_automation_dir: /opt/home_automation
  vars_files: 
    - secrets.yaml
  roles:
    - host_config
    - install_docker
    - clone_home_automation
    - setup_kubernetes
