default_config:

# Text to speech
tts:
  - platform: google_translate

# http: !include config_files/http.yaml
homeassistant: !include config_files/homeassistant.yaml
group: !include config_files/groups.yaml
automation: !include config_files/automations.yaml
script: !include config_files/scripts.yaml
mqtt: !include config_files/mqtt.yaml
light: !include config_files/light.yaml
media_player: !include config_files/media_player.yaml
# weather: !include config_files/weather.yaml
sensor: !include config_files/sensor.yaml
#remote: !include config_files/remote.yaml
switch: !include config_files/switch.yaml
binary_sensor: !include config_files/binary_sensor.yaml
logger: !include config_files/logger.yaml

python_script:

api:

alexa:
  smart_home:
    filter:
      exclude_domains:
        - media_player
