
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
mqtt: !include mqtt.yaml
light: !include light.yaml
media_player: !include media_player.yaml
weather: !include weather.yaml
sensor transport: !include sensor_transport.yaml
sensor river: !include sensor_river.yaml
#remote: !include remote.yaml
switch: !include switch.yaml
