  - platform: broadlink
    host: !secret broadlink_ip
    mac: !secret broadlink_mac
    timeout: 15
    retry: 5
    switches:
      tv_samsung:
        friendly_name: "Samsung Tv Power"
        command_on: 'JgCMAJSSEzYUNhM1FBETERQRExEUERQ1FDUUNRQRExEUERMRFBEUEBQ2ExEUERMRFBETERQREzYUEBQ2EzYTNhM2EzYUNRQABf2VkRQ2EzYTNhMRFBEUEBQRFBETNhM2EzYTERQRFBETERQRExEUNRQRExEUERMRFBEUERM2ExEUNRQ1FDUUNhM2EzYTAA0FAAAAAAAAAAAAAAAA'
        command_off: 'JgCMAJSSEzYUNhM1FBETERQRExEUERQ1FDUUNRQRExEUERMRFBEUEBQ2ExEUERMRFBETERQREzYUEBQ2EzYTNhM2EzYUNRQABf2VkRQ2EzYTNhMRFBEUEBQRFBETNhM2EzYTERQRFBETERQRExEUNRQRExEUERMRFBEUERM2ExEUNRQ1FDUUNhM2EzYTAA0FAAAAAAAAAAAAAAAA'
