- name: check if helm is installed
  shell: which helm
  register: helm_installed
  ignore_errors: true

# NOTE: Ansible has a helm module, which relies on pyhelm on the remote host
# However pyhelm somehow compiles from source when installing and takes foreeeever, so not used...
# ### this takes foreeeeeeever
# - name: install pyhelm
#   pip:
#     executable: pip3
#     name: pyhelm
# ### This is how the ansible helm module would work
# - name: install helm nginx
#   helm:
#     chart:
#       name: stable/nginx-ingress
#       source:
#         type: repo
#         repo: https://helm.nginx.com/stable
#     state: present
#     name: hass-nginx
#     namespace: hass

# source https://mhausenblas.info/kube-rpi/
# "normal" helm installation via snap has porblems on ARM arch
- name: install helm
  shell: |
    export HELM_VERSION={{helm_version}}
    wget https://get.helm.sh/helm-$HELM_VERSION-linux-arm64.tar.gz
    tar xvzf helm-$HELM_VERSION-linux-arm64.tar.gz
    mv linux-arm64/helm /usr/local/bin/helm
    rm -rf linux-arm64 && rm helm-$HELM_VERSION-linux-arm64.tar.gz
  when: helm_installed.rc != 0
  become: yes

- name: add the repo "stable"
  shell: helm repo add stable https://kubernetes-charts.storage.googleapis.com/
  when: helm_installed.rc != 0

- name: add the ingress-nginx repo"
  shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  when: helm_installed.rc != 0

- name: add the repo "jetstack (for cert mananger)"
  shell: helm repo add jetstack https://charts.jetstack.io
  when: helm_installed.rc != 0

- name: update repos
  shell: helm repo update
  when: helm_installed.rc != 0
