- name: install helm
  shell: snap install helm --classic
  become: yes

# this takes foreeeeeeever
- name: install pyhelm
  pip:
    executable: pip3
    name: pyhelm

- name: update repo
  shell: /snap/bin/helm repo update

- name: install helm nginx
  helm:
    chart: 
      name: stable/nginx-ingress
      source:
        type: repo
        repo: https://helm.nginx.com/stable
    state: present
    name: hass-nginx
    namespace: hass

- name: install helm cert manager
  helm:
    chart: stable/cert-manager
    state: present
    name: hass-cert-manager
    namespace: hass

https://cert-manager.io/docs/tutorials/acme/ingress/

install helm as here: https://mhausenblas.info/kube-rpi/
install nginx arm version: https://github.com/kubernetes/ingress-nginx/issues/4876
helm install hass-nginx-ingress stable/nginx-ingress --set controller.image.repository="quay.io/kubernetes-ingress-controller/nginx-ingress-controller-arm64" --set defaultBackend.image.repository="k8s.gcr.io/defaultbackend-arm64" --set controller.service.externalIPs={144.2.115.50} --set rbac.create=true --set controller.publishService.enabled=true --set controller.hostNetwork=true

apply -f ingress.yaml

helm repo add jetstack https://charts.jetstack.io
helm repo update

helm install   cert-manager jetstack/cert-manager   --namespace hass   --version v0.15.1   --set installCRDs=true
apply -f letsencrypt-staging.yaml
apply -f letsencrypt-prod.yaml
