- name: Check whether sshd backup exists
  stat:
    path: "/etc/ssh/sshd_config.bkp"
  register: stat_result

- name: Create sshd_config backup
  command: cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bkp
  when: stat_result.stat.exists == false
  become: yes

- name: replace sshd_config file
  copy:
    src: ../files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    force: yes
    backup: yes
  become: yes
  # when: stat_result.stat.exists == false

- name: restart sshd
  service:
    name: 'sshd'
    state: 'restarted'
  become: yes
